services:
  rebase-labs-database:
    image: postgres
    container_name: rebase-labs-database
    volumes:
      - ./data/db_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=rebase
      - POSTGRES_PASSWORD=123456

  rebase-labs-database-test:
    image: postgres
    container_name: rebase-labs-database-test
    volumes:
      - ./data/db_test:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=rebase
      - POSTGRES_PASSWORD=123456

  rebase-labs-server:
    build: .
    container_name: rebase-labs-server
    working_dir: /app
    volumes:
      - .:/app
      - rubygems:/user/local/bundle
    ports:
      - "3000:3000"
    command: bash -c "bundle install && ruby prepare_database.rb data.csv && ruby server.rb"
    depends_on:
      - rebase-labs-database
      - rebase-labs-database-test

volumes:
  rubygems: