services:
  rebase-labs-database:
    image: postgres
    container_name: rebase-labs-database
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=rebase
      - POSTGRES_PASSWORD=123456

  rebase-labs-server:
    build: .
    container_name: rebase-labs-server
    working_dir: /app
    volumes:
      - .:/app
      - rubygems:/user/local/bundle
    ports:
      - "3000:3000"
    command: bash -c "bundle install && ruby import_from_csv.rb && ruby server.rb"
    depends_on:
      - rebase-labs-database

volumes:
  rubygems: